feat: Done tasks 1, 2, 3, 4
niklonskyi/nodejs-lessons pull request #2
Opened 2023-04-08 14:40 UTC by niklonskyi

Зроблено завдання 1, 2, 3, 4 у TypeScript

2023-04-13 16:16 UTC, ipiwebtech commented
1,2,3 - ok

4 - ви пробували запускати?
тут треба грунтовніше прописати типи, інакше воно не транспілиться в js

2023-04-13 16:24 UTC, ipiwebtech requested changes
task4
- схоже ви не заборонили тип any, тому у вас скрипт запускається

в tsconfig.json має бути  щось таке:
"compilerOptions":{
		. . .
		"noImplicitAny": true,	// заборона any
		. . .
},

- тоді ви побачите кучу помилок при запуску 4 завдання

2023-04-14 18:33 UTC, niklonskyi commented
Так, там була помилка у поверненому типі функціі: string замість function. Я зробив новий комміт, здається все працює нормально

2023-04-22 09:53 UTC, ipiwebtech commented
ще any забороніть в tsconfig.json

"noImplicitAny": true

2023-04-25 09:10 UTC, niklonskyi commented
Чомусь IDE не підсвічувало помилку і компілювалось нормально, я зробив інтерфейс для об'єкту cache, зараз повинно працювати

2023-05-09 12:54 UTC, ipiwebtech approved these changes
ok

2023-05-09 12:54 UTC, merged